spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/market_intel
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Gemini API Key
gemini.api.key=${GEMINI_API_KEY1}
